apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  serviceAccountName: myapp-sa
  containers:
    - name: myapp
      image: myapp-image:latest
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: vault-secrets
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: vault-secrets
              key: password
  volumes:
    - name: vault-secrets
      csi:
        driver: secrets-store.csi.k8s.io
        volumeHandle: "myapp-secrets"
        readOnly: true
