apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-secrets
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault:8200"
    roleName: "myapp-role"
    objects: |
      - objectName: "secret/data/myapp/config"
        objectType: "kv"
        objectVersion: "latest"
        objectKey: "username"
        secretKeyRef: "username"  # This defines the key name inside the pod's environment
      - objectName: "secret/data/myapp/config"
        objectType: "kv"
        objectVersion: "latest"
        objectKey: "password"
        secretKeyRef: "password"

