apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-secrets
spec:
  provider: vault
  secretObjects:
    - secretName: myapp-secrets
      type: Opaque
      data:
        - objectName: "secret/data/myapp/config"
          objectType: "kv"
          objectVersion: "latest"
          key: "username"
          path: "secret/myapp/config"
  parameters:
    vaultAddress: "http://vault:8200"
    roleName: "myapp-role"
